#!/bin/bash
### BEGIN INIT INFO
# Provides:	buttonos
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Setup for the ButtonOS project
### END INIT INFO

# Author: Joseph J. Gunn <gunnjo@curlycloud.com>
NAME="buttonos"
DESC="ButtonOS project setup"
SCRIPTNAME=/etc/init.d/$NAME

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh
. /lib/lsb/init-functions
case "$1" in
	start)
		log_daemon_msg "Starting $0"
		if grep -qs debug /proc/cmdline
		then
			#set user password
		fi
		log_end_msg $?
		
		;;
	stop)
		log_daemon_msg "Stopping $0"
		log_end_msg $?
	;;
esac
