#!/bin/sh
sed -i 's;^1:2345:.*;1:2345:respawn:/sbin/mingetty --autologin buttonuser tty1 linux;s;^[2-6]:23:.*;#&;' /etc/inittab
insserv buttonos
insserv wicdnet
cat <<EOF >>/etc/iceweasel/pref/iceweasel.js
pref("extensions.update.enabled", false);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
lockpref("xpinstall.enabled", false);
EOF

cat <<EOF >>/etc/iceweasel/profile/prefs.js
user_pref("browser.startup.homepage", "http://www.buttonos.org/start");
EOF
