#!/bin/sh
#create a new group that can run these commands
groupadd commondep
#
chown root:commondep /usr/lib/commonde/*
chmod 440 /usr/lib/commonde/*
#
chown root:commondep /usr/lib/commonde/runcommonde
chmod 4550 /usr/lib/commonde/runcommonde
#
usermod -a -G commondep webc

