#! /bin/sh
### BEGIN INIT INFO
# Provides:          lxcfg
# Required-Start:    lxcfg-start
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: unpacks lxcfg
# Description:       unpacks lxcfg
### END INIT INFO

PKGHOME=/tmp
PKG=$PKGHOME/lxde-cfg.tgz

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $0"
	count=10
	while [ -f $PKG ] 
	do
		sleep 1
		count=`expr $count - 1`
		[ $count -lt 0 ] && break
	done
	cd / && tar -xzf $PKG
	log_end_msg $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac


