#! /bin/sh
### BEGIN INIT INFO
# Provides:          lxcfg-start
# Required-Start:    $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: obtains lxcfg
# Description:       obtains lxcfg
### END INIT INFO

PKGHOME=/tmp
PKGFILE=$PKGHOME/lxde-cfg.tgz
CFGURL="http://www.buttonos.org/load/themes/lxde-cfg.tgz"
INSTFILE=/usr/share/lxde/defcfg.tgz

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $0"
	(cd /tmp ; wget --timeout=10 -q $CFGURL -O $PKGFILE.tmp &&
		ln -s $PKGFILE.tmp $PKGFILE ) &
	log_end_msg 0
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac

