#!/usr/bin/env python
import sys
import syslog
from subprocess import check_call, CalledProcessError
from dbus import DBusException
from wicd import dbusmanager

def main(argv):
    iface=argv[1]
    try:
        dbusmanager.connect_to_dbus()
        dbus_ifaces = dbusmanager.get_dbus_ifaces()
        daemon = dbus_ifaces['daemon']
        try:
            check_call(["/sbin/iwgetid", iface]);
            daemon.SetWirelessInterface(iface)
            syslog.syslog(argv[0]+" Setting wireless "+argv[1]);
        except CalledProcessError, e:
            daemon.SetWiredInterface(iface)
            syslog.syslog(argv[0]+" Setting wired "+argv[1]);
    except DBusException:
        print "Can't connect to the daemon."

main(sys.argv)

