#!/bin/sh
media=/media/ButtonOS\ Diags/
postit=http://www.buttonos.org/diags/helpme
set -- `dconf -v | grep "^Building"`
file=$3
while :
do
curl -F "upfile=@$file" $postit && exit 0
[ -e "$media" ] && cp $file "$media" && exit 0
sleep 10
done
