#!/bin/sh
VF=/live/image/.disk/info
DB=cookies.sqlite
V=`awk ' { print $NF } ' < $VF`
U=`uuid`
#iChange to an appropriate directory
if [ -e  $HOME/.mozilla/firefox/*default ]
then
cd $HOME/.mozilla/firefox/*default
else
cd /etc/iceweasel/profile
fi

#no database? no problem!
if [ ! -e $DB ]
then
touch $DB
sqlite3 $DB <<EOF
CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, baseDomain TEXT, name TEXT, value TEXT, host TEXT, path TEXT, expiry INTEGER, lastAccessed INTEGER, creationTime INTEGER, isSecure INTEGER, isHttpOnly INTEGER, CONSTRAINT moz_uniqueid UNIQUE (name, host, path));
EOF
fi
#yum, yum. new cookies!
sqlite3 $DB <<EOF
INSERT INTO moz_cookies (id, baseDomain, name, value, host, path, expiry, lastAccessed, creationTime, isSecure, IsHttpOnly) VALUES ( 1, 'buttonos.org', 'version', '$V', '.buttonos.org', '/', 1415148799, 1337843725798983, 1415148799000, 0,0);
INSERT INTO moz_cookies (id, baseDomain, name, value, host, path, expiry, lastAccessed, creationTime, isSecure, IsHttpOnly) VALUES ( 2, 'buttonos.org', 'id', '$U', '.buttonos.org', '/', 1415148799, 1337843725798983, 1415148799000, 0,0);
EOF
#and make available to curl also
if [ ! -e /home/${LIVE_USERNAME}/.curlrc ]
then
VDIR=/home/${LIVE_USERNAME}
echo "cookie = \"id=$U;version=$V\"" > $VDIR/.curlrc
fi
